name: CI

on:
    pull_request:
    push:
        branches:
            - master

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Run CI
              run: npm run ci

            - name: "Get coverage for badge"
              run: |
                  SUMMARY="$(npm run test-ci | tail -2 | head -1)";
                  TOKENS=($SUMMARY)
                  echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

                  REF=${{ github.ref }}
                  echo "github.ref: $REF"
                  IFS='/' read -ra PATHS <<< "$REF"
                  BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
                  echo $BRANCH_NAME
                  echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV

            - name: Create the Badge
              uses: schneegans/dynamic-badges-action@7142847813c746736c986b42dec98541e49a2cea #v1.7.0
              with:
                  auth: ${{ secrets.GIST_SECRET }}
                  gistID: 04d82ee409900594c4dff542b597999d
                  filename: steampath_coverage.json
                  label: Test Coverage
                  message: ${{ env.COVERAGE }}
                  color: green
                  namedLogo: vitest
